version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_URI=mongodb+srv://lobo:qZSGsxVn2X1L4Pg0@distribuida.bdh8ues.mongodb.net/?retryWrites=true&w=majority&appName=Distribuida
      - JWT_SECRET=a51363afa2010b6a4692a0f1fcf7e2b0bac3d3b4f93a838b95cc3bd84e5701b4
      - EMAIL=openbudgetdistri@outlook.com
      - EMAIL_PASSWORD=.TA#3l3#KKP5"vc-wnqbm?QHU!8_5O}._%[g|FkVNicemf22aW
    depends_on:
      - mongodb
    networks:
      - backend

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DB_URI=mongodb+srv://lobo:qZSGsxVn2X1L4Pg0@distribuida.bdh8ues.mongodb.net/?retryWrites=true&w=majority&appName=Distribuida
      - JWT_SECRET=a51363afa2010b6a4692a0f1fcf7e2b0bac3d3b4f93a838b95cc3bd84e5701b4
    depends_on:
      - mongodb
    networks:
      - backend

  transaction-service:
    build: ./transaction-service
    container_name: transaction-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - DB_URI=mongodb+srv://lobo:qZSGsxVn2X1L4Pg0@distribuida.bdh8ues.mongodb.net/?retryWrites=true&w=majority&appName=Distribuida
      - JWT_SECRET=a51363afa2010b6a4692a0f1fcf7e2b0bac3d3b4f93a838b95cc3bd84e5701b4
    depends_on:
      - mongodb
    networks:
      - backend

  subscription-service:
    build: ./subscription-service
    container_name: subscription-service
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - DB_URI=mongodb+srv://lobo:qZSGsxVn2X1L4Pg0@distribuida.bdh8ues.mongodb.net/?retryWrites=true&w=majority&appName=Distribuida
      - JWT_SECRET=a51363afa2010b6a4692a0f1fcf7e2b0bac3d3b4f93a838b95cc3bd84e5701b4
    depends_on:
      - mongodb
    networks:
      - backend

  debt-service:
    build: ./debt-service
    container_name: debt-service
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
      - DB_URI=mongodb+srv://lobo:qZSGsxVn2X1L4Pg0@distribuida.bdh8ues.mongodb.net/?retryWrites=true&w=majority&appName=Distribuida
      - JWT_SECRET=a51363afa2010b6a4692a0f1fcf7e2b0bac3d3b4f93a838b95cc3bd84e5701b4
    depends_on:
      - mongodb
    networks:
      - backend

  budget-category-service:
    build: ./budget-category-service
    container_name: budget-category-service
    ports:
      - "3005:3005"
    environment:
      - PORT=3005
      - DB_URI=mongodb+srv://lobo:qZSGsxVn2X1L4Pg0@distribuida.bdh8ues.mongodb.net/?retryWrites=true&w=majority&appName=Distribuida
      - JWT_SECRET=a51363afa2010b6a4692a0f1fcf7e2b0bac3d3b4f93a838b95cc3bd84e5701b4
    depends_on:
      - mongodb
    networks:
      - backend

  report-service:
    build: ./report-service
    container_name: report-service
    ports:
      - "3006:3006"
    environment:
      - PORT=3006
      - AUTH_SERVICE_URL=http://auth-service:3000
      - USER_SERVICE_URL=http://user-service:3001
      - TRANSACTION_SERVICE_URL=http://transaction-service:3002
      - SUBSCRIPTION_SERVICE_URL=http://subscription-service:3003
      - DEBT_SERVICE_URL=http://debt-service:3004
      - JWT_SECRET=a51363afa2010b6a4692a0f1fcf7e2b0bac3d3b4f93a838b95cc3bd84e5701b4
    depends_on:
      - mongodb
      - auth-service
      - user-service
      - transaction-service
      - subscription-service
      - debt-service
      - budget-category-service
    networks:
      - backend

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - user-service
      - transaction-service
      - subscription-service
      - debt-service
      - budget-category-service
      - report-service
    networks:
      - backend

networks:
  backend:

volumes:
  mongo-data:
